---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - python
  eslint:
    enabled: false
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- test/
