kafka:
  topic: '$LK_TOPIC'
database:
  type: 'rdbms'
  driver: '$LK_DB_DRIVER'
  host: '$LK_DB_HOST'
  port: '$LK_DB_PORT'
  db: '$LK_DB_NAME'
  user: '$LK_DB_USER'
  password: '$LK_DB_PASS'
  pool_size: '$LK_DB_POOL_SIZE'
cache:
  host: '$LK_CACHE_HOST'
  db: '$LK_CACHE_DB'
  type: '$LK_CACHE_TYPE'
zookeeper:
  hosts:
    - '$LK_ZOOKEEPER_1'
    #- '$LK_ZOOKEEPER_2'
stats:
  type: 'statsd'
  host: '$LK_STATSD_HOST'
  port: 8125
  prefix: '$LK_STATSD_PREFIX'
secret: '$LK_SECRET_KEY'