kafka:
  topic: '$LK_TOPIC'
database:
  type: 'rdbms'
  driver: '$LK_DB_DRIVER'
  host: '$LK_DB_HOST'
  port: '$LK_DB_PORT'
  db: '$LK_DB_NAME'
  user: '$LK_DB_USER'
  password: '$LK_DB_PASS'
  pool_size: '$LK_DB_POOL_SIZE'
cache:
  host: '$LK_CACHE_HOST'
  db: '$LK_CACHE_DB'
  type: '$LK_CACHE_TYPE'
zookeeper:
  hosts:
    - '$LK_ZOOKEEPER_1'
    #- '$LK_ZOOKEEPER_2'
stats:
  type: 'statsd'
  host: '$LK_STATSD_HOST'
  port: 8125
  prefix: '$LK_STATSD_PREFIX'
secret: '$LK_SECRET_KEY'
web:
  type: 'oauth'
  root_url: '$LK_WEB_ROOT_URL'
  insecure: '$LK_WEB_AUTH_INSECURE'
  base: '$LK_WEB_AUTH_BASE'
  path: '$LK_WEB_AUTH_PATH'
  service_id: '$LK_WEB_AUTH_SERVICE_ID'
  service_secret: '$LK_WEB_AUTH_SERVICE_SECRET'
  authorized_url: '$LK_WEB_AUTH_URL'
  token_url: '$LK_WEB_AUTH_TOKEN_URL'
  callback_url: '$LK_WEB_AUTH_CALLBACK_URL'
  unauthorized_url: '$LK_WEB_AUTH_UNAUTH_URL'
  use_floating_menu: '$LK_WEB_USE_FLOATING_MENU'