LK_DB_HOST: 'localhost'
LK_DB_NAME: 'recs'
LK_DB_USER: 'recsuser'
LK_DB_PASS: 'recspass'
LK_DB_POOL_SIZE: '10'
LK_DB_DRIVER: 'postgres+psycopg2'
LK_DB_PORT: '5432'
LK_CACHE_TYPE: 'redis'
LK_CACHE_HOST: 'localhost:6379'
LK_CACHE_DB: '12'
LK_STATSD_HOST: 'localhost'
LK_STATSD_PREFIX: 'recs'
LK_TOPIC: 'test-topic'
LK_ZOOKEEPER_1: 'maggie-zoo-1:2181'
LK_ZOOKEEPER_2: 'maggie-zoo-2:2181'