RECS_DB_HOST: 'localhost'
RECS_DB_NAME: 'recs'
RECS_DB_USER: 'recsuser'
RECS_DB_PASS: 'recspass'
RECS_DB_POOL_SIZE: '10'
RECS_DB_DRIVER: 'postgres+psycopg2'
RECS_DB_PORT: '5432'
RECS_CACHE_TYPE: 'redis'
RECS_CACHE_HOST: 'localhost:6379'
RECS_CACHE_DB: '12'
RECS_STATSD_HOST: 'localhost'
RECS_STATSD_PREFIX: 'recs'
RECS_TOPIC: 'test-topic'
RECS_ZOOKEEPER_1: 'maggie-zoo-1:2181'
RECS_ZOOKEEPER_2: 'maggie-zoo-2:2181'